/*
 * Created on 24 „«— 2016 ( Time 00:25:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "classroom"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="classroom", catalog="mydb" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ClassroomEntity.countAll", query="SELECT COUNT(x) FROM ClassroomEntity x" )
} )
public class ClassroomEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="class_id", nullable=false)
    private Integer    classId      ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="classroom_name", length=45)
    private String     classroomName ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="classroom", targetEntity=StudentEntity.class)
    private List<StudentEntity> listOfStudent;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ClassroomEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setClassId( Integer classId ) {
        this.classId = classId ;
    }
    public Integer getClassId() {
        return this.classId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : classroom_name ( VARCHAR ) 
    public void setClassroomName( String classroomName ) {
        this.classroomName = classroomName;
    }
    public String getClassroomName() {
        return this.classroomName;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfStudent( List<StudentEntity> listOfStudent ) {
        this.listOfStudent = listOfStudent;
    }
    public List<StudentEntity> getListOfStudent() {
        return this.listOfStudent;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(classId);
        sb.append("]:"); 
        sb.append(classroomName);
        return sb.toString(); 
    } 

}
