/*
 * Created on 24 „«— 2016 ( Time 00:25:28 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "student"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="student", catalog="mydb" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="StudentEntity.countAll", query="SELECT COUNT(x) FROM StudentEntity x" )
} )
public class StudentEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="student_id", nullable=false)
    private Integer    studentId    ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="student_balance")
    private BigDecimal studentBalance ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="student_dob")
    private Date       studentDob   ;

    @Column(name="student_gender")
    private Boolean    studentGender ;

    @Column(name="student_name", length=45)
    private String     studentName  ;

	// "classId" (column "class_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="class_id", referencedColumnName="class_id")
    private ClassroomEntity classroom   ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public StudentEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setStudentId( Integer studentId ) {
        this.studentId = studentId ;
    }
    public Integer getStudentId() {
        return this.studentId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : student_balance ( DECIMAL ) 
    public void setStudentBalance( BigDecimal studentBalance ) {
        this.studentBalance = studentBalance;
    }
    public BigDecimal getStudentBalance() {
        return this.studentBalance;
    }

    //--- DATABASE MAPPING : student_dob ( DATETIME ) 
    public void setStudentDob( Date studentDob ) {
        this.studentDob = studentDob;
    }
    public Date getStudentDob() {
        return this.studentDob;
    }

    //--- DATABASE MAPPING : student_gender ( BIT ) 
    public void setStudentGender( Boolean studentGender ) {
        this.studentGender = studentGender;
    }
    public Boolean getStudentGender() {
        return this.studentGender;
    }

    //--- DATABASE MAPPING : student_name ( VARCHAR ) 
    public void setStudentName( String studentName ) {
        this.studentName = studentName;
    }
    public String getStudentName() {
        return this.studentName;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setClassroom( ClassroomEntity classroom ) {
        this.classroom = classroom;
    }
    public ClassroomEntity getClassroom() {
        return this.classroom;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(studentId);
        sb.append("]:"); 
        sb.append(studentBalance);
        sb.append("|");
        sb.append(studentDob);
        sb.append("|");
        sb.append(studentGender);
        sb.append("|");
        sb.append(studentName);
        return sb.toString(); 
    } 

}
